cargo-features = ["profile-overrides"]

[profile.dev.package."*"]
opt-level = 2
debug = true

[workspace]
members = ["client", "core", "render_vk", "render", "macros", "ai",  "ui",  "reaction"]
#"worldgen",